### ISSUE TITLE
Error when adding vehicle restrictions

### ISSUE THREAD

**Issue by larsupb** [hschneid/xfvrp#28]
When adding vehicle restrictions to a customer the VRPPreCheckService crashes with following stack trace:

`Caused by: java.lang.UnsupportedOperationException
    at java.util.AbstractList.remove(AbstractList.java:161)
    at java.util.AbstractList$Itr.remove(AbstractList.java:374)
    at java.util.AbstractCollection.remove(AbstractCollection.java:293)
    at xf.xfvrp.opt.init.precheck.vrp.VRPPreCheckService.removeNode(VRPPreCheckService.java:93)
    at xf.xfvrp.opt.init.precheck.vrp.VRPPreCheckService.checkVehicleType(VRPPreCheckService.java:75)
    at xf.xfvrp.opt.init.precheck.vrp.VRPPreCheckService.precheck(VRPPreCheckService.java:57)`

**Comment by hschneid** [comment]
I will look at it!

**Comment by hschneid** [comment]
@larsupb Is fixed in branch 11_4_3.

Reason: Arrays.asList(...) is returning a special fixed-length list, which is doing a write-through. Removing on this special list type is unsupported.

Shame on me, it was not tested. 👎

**Comment by larsupb** [comment]
At least we're a step further. But sadly still not working in my case ❌ 

Please check my branch on my [fork](https://github.com/larsupb/xfvrp/tree/11_4_4_hackstein) for an updated instance with vehicle restrictions on it. VEHICLE_1 is simply not to be used.

**Comment by hschneid** [comment]
Situation: 
* Given 20 nodes and 2 vehicle types
* but all nodes are only valid for 1 vehicle type
* Thanks for good test data.

Options:
* XFVRP could handle incorrect data input.
** Advantage: Easier for user
** Disadvantage: XFVRP must handle data, which makes not evertime sense. This increase internal complexity.
* XFVRP could check and inform caller, that this makes no sense.
** Advantage: Internal complexity stay easier.
** Disadvantage: User should care about data, which is given to XFVRP.

Solution:
* I took option 2.
* See branch 11_4_4
